default: &default
  database: <%= "co_lab_#{Rails.env}" %>
  adapter: postgresql
  pool: 5
  timeout: 5000 

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  url: <%= ENV["DATABASE_URL"] %>
